[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
solana_contract = "CGU1WsfUbydfjimDfLw5PmJNEaYfLUcaYvk5vZhjGSA2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.shyft.to?api_key=GpR6DTSKjL7YmSIY"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
