[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
solana_contract = "2kX5Vc47ABpaErfFUTzqFDcRs5ZRknYkdHhAtvCt8SbJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=9d1a1939-30d8-46d6-98e2-4e879a4b225a"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
