[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
solana_contract = "5cqLDLSvNPwc2wGNwyZvnUiSqh1gh4PrXNNQP8CmcaFP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://neat-delicate-bush.solana-mainnet.quiknode.pro/d3829ce0c895d3a2487e473dc9da6cc9072190ac/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
