[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_contract = "8p5kaH1np1p1YL7rSXDPFEmrtg5fwGBxEThmztuEB8en"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/adil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
